export const GET_ALL_VIDEOGAMES = "GET_ALL_VIDEOGAMES";
export const GET_GAMES_SUCCESS = "GET_GAMES_SUCCESS"; 
export const GET_GAMES_ERROR = "GET_GAMES_ERROR"

export const SEARCH_GAMES = "SEARCH_GAMES"
export const SEARCH_GAMES_SUCCESS = "SEARCH_GAMES_SUCCESS"
export const SEARCH_GAMES_ERROR = "SEARCH_GAMES_ERROR"

export const GET_GENRE = "GET_GENRE"
export const GET_GENRE_SUCCESS = "GET_GENRE_SUCCESS"
export const GET_GENRE_ERROR = "GET_GENRE_ERROR"

export const GET_PLATFORM = "GET_PLATFORM"
export const GET_PLATFORM_SUCCESS = "GET_PLATFORM_SUCCESS"
export const GET_PLATFORM_ERROR = "GET_PLATFORM_ERROR"

export const GET_GAME_ID = "GET_GAME_ID"
export const GET_GAME_ID_SUCCESS = "GET_GAME_ID_SUCCESS"
export const GET_GAME_ID_ERROR = "GET_GAME_ID_ERROR"

export const ADD_NEW_GAME = "ADD_NEW_GAME"
export const ADD_NEW_GAME_SUCCESS = "ADD_NEW_GAME_SUCCESS"
export const ADD_NEW_GAME_ERROR = "ADD_NEW_GAME_ERROR"

export const RESET = "RESET"

export const FILTER_BY = "FILTER_BY"
export const ORDER_BY = "ORDER_BY"

